services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack3
    ports:
      - "4566:4566"     # LocalStack Gateway
    environment:
      - SERVICES=lambda,apigateway,s3,sqs,dynamodb,ses,events
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_APIGATEWAY=1
      - LOG_LEVEL=INFO
      - DEBUG=1
    volumes:
      - ./lambdas:/var/task
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init:/etc/localstack/init/ready.d
      - ./frontend:/var/frontend
      - ./products.json:/var/products.json:ro
      - ./localstack-data:/var/lib/localstack
